List<String> categoryList = [
  "Home",
  "My List",
  "Available for Download",
  "Action",
  "Anime",
  "Comedies",
  "Crime",
  "Documentaries",
  "Dramas",
  "Fantasy",
  "Fitness",
  "Horror",
  "Kids & Family",
  "Made in South Africa",
  "Music & Musicals",
  "Reality",
  "Romance",
  "Sci-Fi",
  "Stand-Up",
  "Thrillers",
  "Audio Description",
];
List<String> mainCategoryList = [
  "Home",
  "TV Shows",
  "Movies",
];

List<String> movieCategoryList = [
  "All Categories",
  "Available for Download",
  "Action",
  "Anime",
  "Award-Winning",
  "Children & Family",
  "Classics",
  "Comedies",
  "Crime",
  "Documentaries",
  "Dramas",
  "Fantasy",
  "Hollywood",
  "Horror",
  "Independent",
  "Made in Africa",
  "Music & Musicals",
  "Nollywood",
  "Romance",
  "Sci-Fi",
  "Shorts",
  "Sports",
  "Stand-Up Comedy",
  "Thrillers",
  "Audio Description",
];

List<String> tvCategoryList = [
  "All Categories",
  "Available for Download",
  "Action",
  "Anime",
  "Asian",
  "British",
  "Comedies",
  "Crime",
  "Docuseries",
  "Dramas",
  "European",
  "Fitness",
  "Horror",
  "Kids",
  "Reality & Talk",
  "Romance",
  "Sci-Fi & Fantasy",
  "Science & Nature",
  "Teen",
  "The World of The Witcher",
  "Thrillers",
  "US",
  "Audio Description",
];
